twig:
    default_path: '%kernel.project_dir%/templates'
    cache: false
    globals:
        ItemService: '@App\Service\Item\ItemService'
        RivenService: '@App\Service\Item\RivenService'

when@test:
    twig:
        strict_variables: true
